services:
  # Web service (Flask app)
  - type: web
    name: stadthavet-ais
    env: python
    region: frankfurt  # EU region closest to Norway
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python web.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: RENDER
        value: true
      - key: ALLOWED_ORIGINS
        value: https://stad.bringsvor.com
      - key: DATABASE_URL
        fromDatabase:
          name: stadthavet-db
          property: connectionString
      # BARENTSWATCH_CLIENT_ID, BARENTSWATCH_CLIENT_SECRET, MET_CLIENT_ID
      # need to be added manually in Render dashboard as secret env vars

  # Cron job for data collection (runs every 12 hours)
  - type: cron
    name: stadthavet-ais-collector
    env: python
    region: frankfurt  # EU region closest to Norway
    schedule: "0 */12 * * *"  # At minute 0 past every 12th hour
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python barents.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: stadthavet-db
          property: connectionString
      # Same env vars as web service - add in Render dashboard

# PostgreSQL database
databases:
  - name: stadthavet-db
    region: frankfurt  # EU region closest to Norway
    databaseName: stadthavet
    user: stadthavet
